services:
  instafix:
    x-target: apeach
    container_name: misc-instafix
    image: ghcr.io/wikidepia/instafix:main
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 3333:3000
