services:
  umami-db:
    x-target: apeach
    container_name: umami-db
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umami"]
      interval: 60s
      timeout: 10s
      retries: 5
    volumes:
      - $CONFIG_ROOT/umami/db:/var/lib/postgresql/data

  umami:
    container_name: umami
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: unless-stopped
    depends_on:
      umami-db:
        condition: service_healthy
    environment:
      APP_SECRET: $UMAMI_APP_SECRET
      DATABASE_TYPE: postgresql
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
    ports:
      - 3000:3000
