services:
  homepage:
    x-target: apeach
    container_name: lab-homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    environment:
      HOMEPAGE_ALLOWED_HOSTS: $HOST_IP:7676
    ports:
      - 7676:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $CONFIG_ROOT/homepage:/app/config:rw
