version: "2"

services:
  homebridge:
    container_name: homelab-homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ENABLE_AVAHI: 0
      HOMEBRIDGE_CONFIG_UI_PORT: 9999
    volumes:
      - $CONFIG_ROOT/homebridge:/homebridge:rw
    healthcheck:
      test: curl -f localhost:9999 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s

  homepage:
    container_name: homelab-homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    ports:
      - 7676:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $CONFIG_ROOT/homepage:/app/config:rw

  netalertx:
    container_name: homelab-netalertx
    image: jokobsk/netalertx:latest
    network_mode: host
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    environment:
      TZ: $TZ
      PORT: 20211
      HOST_USER_ID: $PUID
      HOST_USER_GID: $PGID
    volumes:
      - $CONFIG_ROOT/netalertx/config:/app/config:rw
      - $CONFIG_ROOT/netalertx/db:/app/db:rw
      - $CONFIG_ROOT/netalertx/logs:/app/front/log:rw
    healthcheck:
      test: curl -f localhost:20211 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s

  pomerium:
    container_name: homelab-pomerium
    image: pomerium/pomerium:v0.26
    restart: always
    ports:
      - 32443:443/tcp
    volumes:
      - $CONFIG_ROOT/pomerium/config.yaml:/pomerium/config.yaml:ro
