version: "2"

services:
  sonarr:
    container_name: media-sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 8989:8989
    volumes:
      - $CONFIG_ROOT/sonarr:/config
      - $DOWNLOADS:/downloads
      # Additional volume mounts for media
      - $MEDIA_ROOT/Anime:/anime
      - $MEDIA_ROOT/TV:/tv

  radarr:
    container_name: media-radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 7878:7878
    volumes:
      - $CONFIG_ROOT/radarr:/config
      - $DOWNLOADS:/downloads
      # Additional volume mounts for media
      - $MEDIA_ROOT/Films:/movies
      - $MEDIA_ROOT/Films FR:/movies-fr

  prowlarr:
    container_name: media-prowlarr
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 9696:9696
    volumes:
      - $CONFIG_ROOT/prowlarr:/config

  mylar:
    container_name: media-mylar
    image: linuxserver/mylar3:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 8090:8090
    volumes:
      - $CONFIG_ROOT/mylar:/config
      - $DOWNLOADS:/downloads
      # Additional volume mounts for media
      - $MEDIA_ROOT/Comics:/comics

  overseerr:
    container_name: media-overseerr
    image: linuxserver/overseerr:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 5055:5055
    volumes:
      - $CONFIG_ROOT/overseerr:/config

  ubooquity:
    container_name: media-ubooquity
    image: linuxserver/ubooquity:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 2202:2202
      - 2203:2203
    volumes:
      - $CONFIG_ROOT/ubooquity:/config
      # Additional volume mounts for media
      - $MEDIA_ROOT/Comics:/comics

  nzbget:
    container_name: media-nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 6789:6789
    volumes:
      - $CONFIG_ROOT/nzbget:/config
      - $DOWNLOADS:/downloads

  transmission:
    container_name: media-transmission
    image: linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TRANSMISSION_WEB_HOME: /web/combustion
    ports:
      - 9091:9091
      - 51413:51413/tcp
      - 51413:51413/udp
    volumes:
      - $CONFIG_ROOT/transmission:/config
      - $DOWNLOADS/.transmission:/downloads/.transmission
      # Additional volume mount for web ui
      - $CONFIG_ROOT/transmission/web:/web

  jdownloader:
    container_name: media-jdownloader
    image: jlesage/jdownloader-2:latest
    restart: unless-stopped
    mem_limit: 4g
    cpu_shares: 768
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
    ports:
      - 5800:5800
    volumes:
      - $CONFIG_ROOT/jdownloader:/config
      - $DOWNLOADS:/output

  tautulli:
    container_name: media-tautulli
    image: ghcr.io/tautulli/tautulli
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 8181:8181
    volumes:
      - $CONFIG_ROOT/tautulli:/config

  isponsorblocktv:
    container_name: media-isponsorblocktv
    image: ghcr.io/dmunozv04/isponsorblocktv:latest
    restart: unless-stopped
    volumes:
      - $CONFIG_ROOT/isponsorblocktv:/app/data

  shinkro:
    container_name: media-shinkro
    image: ghcr.io/varoop/shinkro:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # Required for first start
      SHINKRO_USERNAME: shinkro
      SHINKRO_PASSWORD: shinkro
      PLEX_USERNAME: dhaya
      ANIME_LIBRARIES: Anime
    ports:
      - 7011:7011
    volumes:
      - $CONFIG_ROOT/shinkro:/config
