services:
  mylar:
    container_name: media-mylar
    image: linuxserver/mylar3:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 8090:8090
    volumes:
      - $CONFIG_ROOT/mylar:/config
      - $DOWNLOADS:/downloads
      # Additional volume mounts for media
      - $MEDIA_ROOT/Comics:/comics
