services:
  shinkro:
    container_name: media-shinkro
    image: ghcr.io/varoop/shinkro:latest
    restart: unless-stopped
    user: $PUID:$PGID
    environment:
      TZ: $TZ
      SHINKRO_BASE_URL: /shinkro
    ports:
      - 7011:7011
    volumes:
      - $CONFIG_ROOT/shinkro:/config

