services:
  comfyui:
    x-target: ridge
    container_name: comfyui
    image: mmartial/comfyui-nvidia-docker:ubuntu24_cuda13.0-latest
    restart: unless-stopped
    environment:
      WANTED_UID: 0
      WANTED_GID: 0
      BASE_DIRECTORY: /basedir
      SECURITY_LEVEL: normal
      LD_LIBRARY_PATH: /usr/lib/wsl/lib
      COMFY_CMDLINE_EXTRA: --lowvram
      USE_UV: true
    ports:
      - 8188:8188
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      - $CONFIG_ROOT_RIDGE/comfyui/run:/comfy/mnt
      - $CONFIG_ROOT_RIDGE/comfyui/basedir:/basedir
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
